// <auto-generated />
using IntalioTaskDB.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace IntalioTaskDB.Migrations
{
    [DbContext(typeof(intalioContext))]
    [Migration("20211221073518_intalio")]
    partial class intalio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IntalioTaskCore.Entities.countries", b =>
                {
                    b.Property<int>("country_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("country_name")
                        .HasColumnType("text");

                    b.HasKey("country_code");

                    b.ToTable("Countries");
                });
#pragma warning restore 612, 618
        }
    }
}
